const SUPABASE_URL = 'https://diqbmyqvuyollvlvjniz.supabase.co';
const SUPABASE_KEY = 'sb_publishable_R_XGqN5PlehELFz7u3fgeg_ekGPb38Z';
const app = document.querySelector('#app');
const state = { session: null, surveys: [], questions: [], responses: [], selectedSurvey: null, publicSurvey: null, publicQuestions: [], answers: {}, step: 0 };

function esc(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600);}
function formatDate(value){return new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeStyle:'short',timeZone:'America/Mexico_City'}).format(new Date(value));}
function slugify(value){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,70);}

async function api(path,{method='GET',body,auth=true,headers={}}={}){
  const token=auth&&state.session?.access_token?state.session.access_token:SUPABASE_KEY;
  const response=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{method,headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json',...headers},body:body===undefined?undefined:JSON.stringify(body)});
  if(!response.ok){let detail='';try{detail=(await response.json()).message||'';}catch{}throw new Error(detail||`Error ${response.status}`);}
  if(response.status===204)return null;
  const text=await response.text();return text?JSON.parse(text):null;
}

async function signIn(email,password){
  const response=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})});
  const data=await response.json();if(!response.ok)throw new Error(data.error_description||data.msg||'No fue posible iniciar sesión');
  state.session=data;localStorage.setItem('smsurvey_session',JSON.stringify(data));return data;
}
async function refreshSession(){
  if(!state.session?.refresh_token)return false;
  const response=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:state.session.refresh_token})});
  if(!response.ok)return false;state.session=await response.json();localStorage.setItem('smsurvey_session',JSON.stringify(state.session));return true;
}
function logout(){state.session=null;localStorage.removeItem('smsurvey_session');location.hash='admin';renderRoute();}

function topbar(admin=false){return `<header class="topbar"><a class="brand" href="#home" aria-label="SMSURVEY"><span>SM</span>SURVEY</a><div class="spacer"></div>${admin?`<span class="small muted">${esc(state.session?.user?.email||'Administrador')}</span><button class="btn ghost" data-action="logout">Salir</button>`:`<a class="btn secondary" href="#admin">Administrar</a>`}</header>`;}

async function renderHome(){
  app.innerHTML=`<div class="shell">${topbar()}<section class="hero"><div class="eyebrow">SM Soluciones</div><h1>SMSURVEY</h1><p>Creamos diagnósticos claros para convertir respuestas en decisiones.</p></section><main class="container"><div class="section-title"><h2>Encuestas disponibles</h2></div><div id="surveyGrid" class="grid"><div class="card empty">Cargando…</div></div></main></div>`;
  try{const surveys=await api('sm_encuestas?activa=eq.true&select=id,slug,titulo,descripcion,cliente_nombre,cliente_color&order=created_at.desc',{auth:false});document.querySelector('#surveyGrid').innerHTML=surveys.length?surveys.map(s=>`<article class="card survey-card"><span class="badge">${esc(s.cliente_nombre)}</span><h2>${esc(s.titulo)}</h2><p>${esc(s.descripcion||'')}</p><a class="btn" href="#survey/${encodeURIComponent(s.slug)}">Responder encuesta</a></article>`).join(''):`<div class="card empty">No hay encuestas activas.</div>`;}catch(error){document.querySelector('#surveyGrid').innerHTML=`<div class="card empty error">${esc(error.message)}</div>`;}
}

function renderLogin(){app.innerHTML=`<main class="login"><form class="login-card" id="loginForm"><div class="eyebrow">Acceso administrativo</div><h1>SMSURVEY</h1><p class="muted small">Crea encuestas y consulta respuestas con tu cuenta autorizada.</p><div class="field"><label for="email">Correo</label><input class="input" id="email" type="email" autocomplete="username" required></div><div class="field"><label for="password">Contraseña</label><input class="input" id="password" type="password" autocomplete="current-password" required minlength="6"></div><p class="error" id="loginError"></p><button class="btn" type="submit">Entrar al panel</button><a class="btn ghost" href="#home">Volver</a></form></main>`;}

async function ensureAdmin(){
  if(!state.session)return false;
  if(Date.now()/1000>=(state.session.expires_at||0)-30&&!await refreshSession()){logout();return false;}
  try{await api('sm_survey_admins?user_id=eq.'+encodeURIComponent(state.session.user.id)+'&select=user_id&limit=1');return true;}catch{return false;}
}

async function loadAdmin(){
  const [surveys,questions,responses]=await Promise.all([api('sm_encuestas?select=*&order=created_at.desc'),api('sm_preguntas?select=*&order=orden.asc'),api('sm_respuestas?select=*&order=created_at.desc')]);
  state.surveys=surveys;state.questions=questions;state.responses=responses;
}
function adminShell(content,active='surveys'){return `<div class="shell">${topbar(true)}<div class="admin-layout"><aside class="sidebar"><button class="navbtn ${active==='surveys'?'active':''}" data-admin-tab="surveys">Encuestas</button><button class="navbtn ${active==='responses'?'active':''}" data-admin-tab="responses">Respuestas</button></aside><main class="admin-main">${content}</main></div></div>`;}
function surveyCounts(id){return {questions:state.questions.filter(q=>q.encuesta_id===id).length,responses:state.responses.filter(r=>r.encuesta_id===id).length};}

function renderAdminSurveys(){
  const rows=state.surveys.map(s=>{const c=surveyCounts(s.id);return `<tr><td><strong>${esc(s.titulo)}</strong><div class="small muted">${esc(s.cliente_nombre)} · /#survey/${esc(s.slug)}</div></td><td><span class="badge ${s.activa?'ok':'off'}">${s.activa?'Publicada':'Borrador'}</span></td><td>${c.questions}</td><td>${c.responses}</td><td><div class="actions"><button class="linkbtn" data-edit-survey="${s.id}">Editar</button><button class="linkbtn" data-view-responses="${s.id}">Respuestas</button><button class="linkbtn" data-copy-link="${esc(s.slug)}">Copiar enlace</button></div></td></tr>`;}).join('');
  app.innerHTML=adminShell(`<div class="section-title"><div><h1>Encuestas</h1><div class="muted small">Crea, edita y publica diagnósticos.</div></div><div class="spacer"></div><button class="btn" data-new-survey>Nueva encuesta</button></div><div class="stats"><div class="stat"><strong>${state.surveys.length}</strong><span>Encuestas</span></div><div class="stat"><strong>${state.questions.length}</strong><span>Preguntas</span></div><div class="stat"><strong>${state.responses.length}</strong><span>Respuestas</span></div></div><div class="table-wrap"><table><thead><tr><th>Encuesta</th><th>Estado</th><th>Preguntas</th><th>Respuestas</th><th>Acciones</th></tr></thead><tbody>${rows||'<tr><td colspan="5" class="empty">Aún no hay encuestas.</td></tr>'}</tbody></table></div>`,'surveys');
}

function renderSurveyEditor(id=null){
  const survey=id?state.surveys.find(s=>s.id===id):null;state.selectedSurvey=survey||null;const qs=survey?state.questions.filter(q=>q.encuesta_id===survey.id).sort((a,b)=>a.orden-b.orden):[];
  const questions=survey?`<section class="card"><div class="section-title"><h2>Preguntas</h2><div class="spacer"></div><button class="btn secondary" data-add-question>Agregar pregunta</button></div>${qs.map((q,i)=>`<article class="question"><div class="question-head"><strong>${i+1}. ${esc(q.pregunta)}</strong><button class="linkbtn" data-edit-question="${q.id}">Editar</button><button class="linkbtn" data-move-question="${q.id}" data-direction="up" ${i===0?'disabled':''}>↑</button><button class="linkbtn" data-move-question="${q.id}" data-direction="down" ${i===qs.length-1?'disabled':''}>↓</button><button class="linkbtn" data-delete-question="${q.id}">Eliminar</button></div><div class="question-meta">${typeLabel(q.tipo)} · ${q.requerida?'Requerida':'Opcional'}</div></article>`).join('')||'<div class="empty">Agrega la primera pregunta.</div>'}</section>`:`<section class="card empty">Guarda la encuesta para agregar preguntas.</section>`;
  app.innerHTML=adminShell(`<div class="section-title"><button class="btn ghost" data-admin-tab="surveys">← Volver</button><h1>${survey?'Editar encuesta':'Nueva encuesta'}</h1></div><div class="editor-grid"><form class="card" id="surveyForm"><input type="hidden" name="id" value="${esc(survey?.id||'')}"><div class="field"><label>Título</label><input class="input" name="titulo" required maxlength="140" value="${esc(survey?.titulo||'')}"></div><div class="field"><label>Cliente o proyecto</label><input class="input" name="cliente_nombre" required maxlength="100" value="${esc(survey?.cliente_nombre||'')}"></div><div class="field"><label>Descripción</label><textarea class="input" name="descripcion" maxlength="500">${esc(survey?.descripcion||'')}</textarea></div><div class="field"><label>Identificador del enlace</label><input class="input" name="slug" required maxlength="70" pattern="[a-z0-9-]+" value="${esc(survey?.slug||'')}"><span class="small muted">Sólo minúsculas, números y guiones.</span></div><div class="field"><label>Color</label><input class="input" name="cliente_color" type="color" value="${esc(survey?.cliente_color||'#2563EB')}"></div><label class="option"><input name="activa" type="checkbox" ${survey?.activa?'checked':''}> Publicar encuesta</label><div class="btnrow"><button class="btn" type="button" data-save-survey>Guardar encuesta</button>${survey?`<a class="btn ghost" target="_blank" rel="noopener" href="#survey/${encodeURIComponent(survey.slug)}">Vista pública</a>`:''}</div></form>${questions}</div>`,'surveys');
}

function typeLabel(type){return ({texto:'Texto libre',seleccion:'Selección única',opcion_multiple:'Selección múltiple',si_no:'Sí / No',escala:'Escala 1 a 5'})[type]||type;}
function openQuestionModal(question=null){
  const needsOptions=['seleccion','opcion_multiple'].includes(question?.tipo);document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" data-close-modal><form class="modal" id="questionForm" data-question-id="${esc(question?.id||'')}"><div class="section-title"><h2>${question?'Editar':'Nueva'} pregunta</h2><div class="spacer"></div><button type="button" class="btn ghost" data-close-modal>Cerrar</button></div><div class="field"><label>Pregunta</label><textarea class="input" name="pregunta" required maxlength="500">${esc(question?.pregunta||'')}</textarea></div><div class="field"><label>Tipo</label><select class="input" name="tipo"><option value="texto">Texto libre</option><option value="seleccion">Selección única</option><option value="opcion_multiple">Selección múltiple</option><option value="si_no">Sí / No</option><option value="escala">Escala 1 a 5</option></select></div><div class="field" id="optionsField" ${needsOptions?'':'hidden'}><label>Opciones (una por línea)</label><textarea class="input" name="opciones">${esc((question?.opciones||[]).join('\n'))}</textarea></div><label class="option"><input name="requerida" type="checkbox" ${question?.requerida!==false?'checked':''}> Respuesta requerida</label><button class="btn" type="submit">Guardar pregunta</button></form></div>`);const form=document.querySelector('#questionForm');form.tipo.value=question?.tipo||'texto';}

function renderResponses(surveyId=null){
  const selected=surveyId?state.surveys.find(s=>s.id===surveyId):null;const responses=selected?state.responses.filter(r=>r.encuesta_id===selected.id):state.responses;const rows=responses.map((r,i)=>`<tr><td>${i+1}</td><td><strong>${esc(r.respondente_nombre||'Anónimo')}</strong></td><td>${esc(r.respondente_area||'—')}</td><td>${formatDate(r.created_at)}</td><td><button class="linkbtn" data-open-response="${r.id}">Ver</button></td></tr>`).join('');
  app.innerHTML=adminShell(`<div class="section-title"><div><h1>Respuestas</h1><div class="muted small">${selected?esc(selected.titulo):'Todas las encuestas'}</div></div><div class="spacer"></div><select class="input" id="responseSurvey" style="width:auto"><option value="">Todas</option>${state.surveys.map(s=>`<option value="${s.id}" ${s.id===surveyId?'selected':''}>${esc(s.titulo)}</option>`).join('')}</select><button class="btn secondary" data-export-csv="${surveyId||''}">Exportar CSV</button></div><div class="table-wrap"><table><thead><tr><th>#</th><th>Nombre</th><th>Área</th><th>Fecha</th><th></th></tr></thead><tbody>${rows||'<tr><td colspan="5" class="empty">No hay respuestas.</td></tr>'}</tbody></table></div>`,'responses');
}

function openResponse(id){const response=state.responses.find(r=>r.id===id);if(!response)return;const survey=state.surveys.find(s=>s.id===response.encuesta_id);const qs=state.questions.filter(q=>q.encuesta_id===response.encuesta_id).sort((a,b)=>a.orden-b.orden);document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" data-close-modal><div class="modal"><div class="section-title"><div><h2>${esc(response.respondente_nombre||'Anónimo')}</h2><div class="small muted">${esc(survey?.titulo||'')} · ${formatDate(response.created_at)}</div></div><div class="spacer"></div><button class="btn ghost" data-close-modal>Cerrar</button></div><dl>${qs.map(q=>{const v=response.respuestas?.[q.id];return v===undefined||v===null||v===''?'':`<div class="response-item"><dt>${esc(q.pregunta)}</dt><dd>${esc(Array.isArray(v)?v.join(', '):v)}</dd></div>`;}).join('')}</dl></div></div>`);}

async function renderAdmin(){if(!await ensureAdmin()){renderLogin();return;}app.innerHTML=`${topbar(true)}<div class="empty">Cargando panel…</div>`;try{await loadAdmin();renderAdminSurveys();}catch(error){app.innerHTML=adminShell(`<div class="card empty error">${esc(error.message)}</div>`);}}

async function loadPublicSurvey(slug){const surveys=await api(`sm_encuestas?slug=eq.${encodeURIComponent(slug)}&activa=eq.true&select=*`,{auth:false});if(!surveys[0])throw new Error('Encuesta no encontrada o no publicada.');state.publicSurvey=surveys[0];state.publicQuestions=await api(`sm_preguntas?encuesta_id=eq.${surveys[0].id}&select=*&order=orden.asc`,{auth:false});state.answers={};state.step=0;}
function renderPublicQuestion(){
  const s=state.publicSurvey,qs=state.publicQuestions,q=qs[state.step];if(!q){app.innerHTML=`<div class="survey-wrap">${topbar()}<div class="card empty">Esta encuesta aún no tiene preguntas.</div></div>`;return;}const value=state.answers[q.id];let input='';
  if(q.tipo==='texto')input=`<textarea class="input" id="textAnswer" maxlength="2000" placeholder="Escribe tu respuesta">${esc(value||'')}</textarea>`;
  if(['seleccion','opcion_multiple'].includes(q.tipo))input=(q.opciones||[]).map(o=>`<button class="option ${(Array.isArray(value)?value.includes(o):value===o)?'selected':''}" data-public-option="${esc(o)}">${esc(o)}</button>`).join('');
  if(q.tipo==='si_no')input=['Sí','No'].map(o=>`<button class="option ${value===o?'selected':''}" data-public-option="${o}">${o}</button>`).join('');
  if(q.tipo==='escala')input=`<div class="scale">${[1,2,3,4,5].map(o=>`<button class="option ${value===o?'selected':''}" data-public-scale="${o}">${o}</button>`).join('')}</div>`;
  app.innerHTML=`<div class="survey-wrap"><header class="survey-head"><div><div class="eyebrow">${esc(s.cliente_nombre)}</div><h1>${esc(s.titulo)}</h1><div class="small muted">Pregunta ${state.step+1} de ${qs.length}</div><div class="progress"><span style="width:${((state.step+1)/qs.length)*100}%"></span></div></div></header><main class="survey-form"><article class="answer-card"><span class="badge">${typeLabel(q.tipo)}</span><h2>${esc(q.pregunta)} ${q.requerida?'<span class="error">*</span>':''}</h2>${input}</article></main><nav class="survey-nav">${state.step?'<button class="btn ghost" data-public-prev>Anterior</button>':''}<button class="btn" data-public-next>${state.step===qs.length-1?'Enviar':'Siguiente'}</button></nav></div>`;
}
async function renderPublicSurvey(slug){app.innerHTML='<div class="empty">Cargando encuesta…</div>';try{await loadPublicSurvey(slug);renderPublicQuestion();}catch(error){app.innerHTML=`<div class="survey-wrap">${topbar()}<main class="container"><div class="card empty error">${esc(error.message)}</div></main></div>`;}}
function saveTextAnswer(){const q=state.publicQuestions[state.step],el=document.querySelector('#textAnswer');if(q?.tipo==='texto'&&el)state.answers[q.id]=el.value.trim();}
async function nextPublic(){saveTextAnswer();const q=state.publicQuestions[state.step],v=state.answers[q.id];if(q.requerida&&(v===undefined||v===''||(Array.isArray(v)&&!v.length))){toast('Esta pregunta es requerida');return;}if(state.step<state.publicQuestions.length-1){state.step++;renderPublicQuestion();return;}const first=state.publicQuestions[0],second=state.publicQuestions[1];const payload={encuesta_id:state.publicSurvey.id,respondente_nombre:String(state.answers[first?.id]||'Anónimo').slice(0,200),respondente_area:String(state.answers[second?.id]||'Sin área').slice(0,200),respuestas:state.answers,completada:true};const button=document.querySelector('[data-public-next]');button.disabled=true;button.textContent='Enviando…';try{await api('sm_respuestas',{method:'POST',body:payload,auth:false,headers:{Prefer:'return=minimal'}});fetch('/api/notify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({survey:state.publicSurvey.titulo,name:payload.respondente_nombre,area:payload.respondente_area})}).catch(()=>{});app.innerHTML=`<div class="survey-wrap">${topbar()}<main class="container"><div class="card success"><div class="check">✓</div><h1>¡Gracias!</h1><p class="muted">Tus respuestas fueron registradas correctamente.</p></div></main></div>`;}catch(error){toast(error.message);button.disabled=false;button.textContent='Enviar';}}

function csvCell(value){let s=String(value??'');if(/^[=+\-@]/.test(s))s="'"+s;return `"${s.replace(/"/g,'""')}"`;}
function exportCSV(surveyId=''){const surveys=surveyId?state.surveys.filter(s=>s.id===surveyId):state.surveys;const rows=[];surveys.forEach(s=>{const qs=state.questions.filter(q=>q.encuesta_id===s.id).sort((a,b)=>a.orden-b.orden);const headers=['Encuesta','Nombre','Área','Fecha',...qs.map(q=>q.pregunta)];rows.push(headers.map(csvCell).join(','));state.responses.filter(r=>r.encuesta_id===s.id).forEach(r=>rows.push([s.titulo,r.respondente_nombre,r.respondente_area,formatDate(r.created_at),...qs.map(q=>{const v=r.respuestas?.[q.id];return Array.isArray(v)?v.join('; '):v;})].map(csvCell).join(',')));rows.push('');});const blob=new Blob(['\ufeff'+rows.join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='SMSURVEY-respuestas.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

async function saveSurvey(form){if(!form.reportValidity())return;const button=form.querySelector('[data-save-survey]');button.disabled=true;button.textContent='Guardando…';try{const data=Object.fromEntries(new FormData(form));const id=data.id;const payload={titulo:data.titulo.trim(),cliente_nombre:data.cliente_nombre.trim(),descripcion:data.descripcion.trim(),slug:slugify(data.slug||data.titulo),cliente_color:data.cliente_color,activa:data.activa==='on',updated_at:new Date().toISOString()};if(!payload.slug)throw new Error('El identificador del enlace no es válido.');const saved=id?await api(`sm_encuestas?id=eq.${encodeURIComponent(id)}&select=*`,{method:'PATCH',body:payload,headers:{Prefer:'return=representation'}}):await api('sm_encuestas?select=*',{method:'POST',body:payload,headers:{Prefer:'return=representation'}});if(!Array.isArray(saved)||saved.length!==1)throw new Error('La encuesta no fue actualizada. Intenta nuevamente.');await loadAdmin();renderSurveyEditor(saved[0].id);toast('Encuesta guardada correctamente');}catch(error){button.disabled=false;button.textContent='Guardar encuesta';throw error;}}
async function saveQuestion(form){const data=new FormData(form),id=form.dataset.questionId,qs=state.questions.filter(q=>q.encuesta_id===state.selectedSurvey.id);const type=data.get('tipo');const payload={encuesta_id:state.selectedSurvey.id,pregunta:String(data.get('pregunta')).trim(),tipo:type,requerida:data.get('requerida')==='on',opciones:['seleccion','opcion_multiple'].includes(type)?String(data.get('opciones')).split('\n').map(v=>v.trim()).filter(Boolean):null};if(!id)payload.orden=qs.length+1;if(id)await api(`sm_preguntas?id=eq.${id}`,{method:'PATCH',body:payload,headers:{Prefer:'return=minimal'}});else await api('sm_preguntas',{method:'POST',body:payload,headers:{Prefer:'return=minimal'}});document.querySelector('.modal-backdrop')?.remove();await loadAdmin();renderSurveyEditor(state.selectedSurvey.id);toast('Pregunta guardada');}
async function moveQuestion(id,direction){const qs=state.questions.filter(q=>q.encuesta_id===state.selectedSurvey.id).sort((a,b)=>a.orden-b.orden),index=qs.findIndex(q=>q.id===id),other=direction==='up'?index-1:index+1;if(index<0||other<0||other>=qs.length)return;await Promise.all([api(`sm_preguntas?id=eq.${qs[index].id}`,{method:'PATCH',body:{orden:qs[other].orden},headers:{Prefer:'return=minimal'}}),api(`sm_preguntas?id=eq.${qs[other].id}`,{method:'PATCH',body:{orden:qs[index].orden},headers:{Prefer:'return=minimal'}})]);await loadAdmin();renderSurveyEditor(state.selectedSurvey.id);}

document.addEventListener('submit',async e=>{e.preventDefault();try{if(e.target.id==='loginForm'){const button=e.target.querySelector('button[type=submit]');button.disabled=true;await signIn(e.target.email.value.trim(),e.target.password.value);if(!await ensureAdmin())throw new Error('Esta cuenta no está autorizada para SMSURVEY.');await renderAdmin();}if(e.target.id==='surveyForm')await saveSurvey(e.target);if(e.target.id==='questionForm')await saveQuestion(e.target);}catch(error){const target=document.querySelector('#loginError');if(target)target.textContent=error.message;else toast(error.message);}});
document.addEventListener('change',e=>{if(e.target.name==='tipo')document.querySelector('#optionsField').hidden=!['seleccion','opcion_multiple'].includes(e.target.value);if(e.target.id==='responseSurvey')renderResponses(e.target.value||null);});
document.addEventListener('click',async e=>{
  const el=e.target.closest('button,a');if(!el)return;
  if(el.dataset.action==='logout')logout();
  if(el.hasAttribute('data-save-survey'))try{await saveSurvey(el.closest('form'));}catch(error){toast(error.message);}
  if(el.dataset.adminTab==='surveys')renderAdminSurveys();if(el.dataset.adminTab==='responses')renderResponses();
  if(el.hasAttribute('data-new-survey'))renderSurveyEditor();if(el.dataset.editSurvey)renderSurveyEditor(el.dataset.editSurvey);if(el.dataset.viewResponses)renderResponses(el.dataset.viewResponses);
  if(el.dataset.copyLink){await navigator.clipboard.writeText(`${location.origin}${location.pathname}#survey/${el.dataset.copyLink}`);toast('Enlace copiado');}
  if(el.hasAttribute('data-add-question'))openQuestionModal();if(el.dataset.editQuestion)openQuestionModal(state.questions.find(q=>q.id===el.dataset.editQuestion));
  if(el.dataset.moveQuestion)try{await moveQuestion(el.dataset.moveQuestion,el.dataset.direction);}catch(error){toast(error.message);}
  if(el.dataset.deleteQuestion&&confirm('¿Eliminar esta pregunta?'))try{await api(`sm_preguntas?id=eq.${el.dataset.deleteQuestion}`,{method:'DELETE',headers:{Prefer:'return=minimal'}});await loadAdmin();renderSurveyEditor(state.selectedSurvey.id);}catch(error){toast(error.message);}
  if(el.dataset.openResponse)openResponse(el.dataset.openResponse);if(el.dataset.exportCsv!==undefined)exportCSV(el.dataset.exportCsv);
  if(el.hasAttribute('data-close-modal'))e.target.closest('.modal-backdrop')?.remove();
  if(el.dataset.publicOption!==undefined){const q=state.publicQuestions[state.step];if(q.tipo==='opcion_multiple'){const values=Array.isArray(state.answers[q.id])?[...state.answers[q.id]]:[],i=values.indexOf(el.dataset.publicOption);i>=0?values.splice(i,1):values.push(el.dataset.publicOption);state.answers[q.id]=values;}else state.answers[q.id]=el.dataset.publicOption;renderPublicQuestion();}
  if(el.dataset.publicScale){state.answers[state.publicQuestions[state.step].id]=Number(el.dataset.publicScale);renderPublicQuestion();}
  if(el.hasAttribute('data-public-prev')){saveTextAnswer();state.step--;renderPublicQuestion();}if(el.hasAttribute('data-public-next'))await nextPublic();
});

async function renderRoute(){document.querySelector('.modal-backdrop')?.remove();const hash=location.hash.slice(1)||'home';if(hash==='home')return renderHome();if(hash==='admin')return renderAdmin();if(hash.startsWith('survey/'))return renderPublicSurvey(decodeURIComponent(hash.slice(7)));return renderHome();}
try{state.session=JSON.parse(localStorage.getItem('smsurvey_session')||'null');}catch{localStorage.removeItem('smsurvey_session');}
window.addEventListener('hashchange',renderRoute);renderRoute();
